# Generated by Django 4.1.4 on 2022-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyname', models.CharField(max_length=240, null=True)),
                ('storysrc', models.CharField(max_length=240, null=True)),
                ('content', models.CharField(max_length=240, null=True)),
                ('bookphoto', models.FileField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
